### PR TITLE
Feature/d3 storybook

### PR DESCRIPTION
**Pull request by Blakidarkness**
Created code and stories for MultilineChart and HorizontalBarChart using d3:

- Updated dependencies
- Rebuild visualizations package
- Added yarn storybook script to root
- Created types for each chart
- Created stories for each chart

### CODE REVIEW

**Review by cmbirk — CHANGES_REQUESTED** [review]
@Blakidarkness would you remove any of the stories that we aren't using? There seem to be a bunch of additional code here not related to D3.

We also need to run the visualizations off of the example data dump file instead of hard-coding the values into the stories.

**Comment by Blakidarkness** [comment]
Changes done:

- Custom webpack config to adding a loader to handle .csv imports since storybook only allows media assets
- Stories built from file, had to ignore the import line checking 
- File modified to add dates with distinct years
- Removed unrelated code

**Review by cmbirk — CHANGES_REQUESTED** [review]
For the horizontal bar chart, can we sort by total value desc ( highest at the top )

**Comment by Blakidarkness** [comment]
Changes done:

- Horizontal bar chart shown on descendant order
- Horizontal bar chart  labels truncated if value exceeds margins
- Scale fixed to show correct bar size by adjusting `xScale` domain
- Changed sample records  on story to better chart appreciation

**Review by cmbirk — APPROVED** [review]

**Pull request merged**
